### ISSUE TITLE
Unable to load JSon Configuration

### ISSUE THREAD

**Issue by ADtt** [GavickPro/News-Show-Pro-GK5#268]
Hello,

I have just installed News Show Pro 1.8.1 on a fresh Joomla 3.4 installation.
The Load and Save JSon configuration (Basic settings tab) buttons doesn't seem to work, nothing happens on click and a javascript error appears in the Chrome console : 
Uncaught TypeError: undefined is not a function in class.configmanager.js line 36

This seem to be related with Joomla 3.4 : the buttons are working with NSP 1.8.1 on older Joomla installations.

Could you please check this ?

Regards

Thierry

**Comment by dziudek** [comment]
Hello,

Thank you for your feedback - please apply the following fix: https://github.com/GavickPro/News-Show-Pro-GK5/commit/45516eae5af51dd9acb4dccd6d0d0a8b157544e2

We will include it in the nearest release.

**Comment by ADtt** [comment]
Hello,

Thank you for the fix, but unfortunately it doesn't seem to work.
There are no more javascript errors and the admin page now reloads, but : 
- When you click on "Load", the following message appears : Selected file doesn't exist (and the configuration isn't loaded)
- When you click on "Save", no error message, but the file is saved as "undefined.json" whatever the name you typed
- When you click on "Delete" the following message appears : undefined selected configuration file is not available. Please check the config directory. (and the configuration isn't deleted)
This happens on a fresh Joomla 1.4+GK module installation, with any json configuration sample file.

I hope you can find out how to fix this.

Regards,

Thierry

**Comment by dziudek** [comment]
You right - fied version of the file is here: https://github.com/GavickPro/News-Show-Pro-GK5/blob/J!3.0_compatible/mod_news_pro_gk5/admin/class.configmanager.js

**Comment by ADtt** [comment]
Thanks a lot ! It works now.
